### ISSUE TITLE
Terminology Help show Not Found Error

### ISSUE THREAD

**Issue by gammonpeter** [MauroDataMapper/mdm-ui#101]
Click on a terminology and select help it shows a not found error

**Comment by pjmonks** [comment]
@jamesrwelch The help icons in MDM all load the old wiki at https://modelcatalogue.cs.ox.ac.uk/wiki, but this is what is returning the 404, perhaps because it was taken down.

Should we now be redirecting help topics to the new https://maurodatamapper.github.io/ documentation site? If so, it may be more appropriate to not use a modal dialog with an iframe inside, but open the relevant help link as a new browser tab.

There may also be the issue of trying to map previous help topics with current pages available in the documentation site.

What are your thoughts?

**Comment by pjmonks** [comment]
As discussed in our standup meeting with @jamesrwelch , the following should now happen:

* Change the help icons to no longer load a modal dialog with iframe
* Instead, navigate to a new browser tab to an appropriate page in the main MDM documentation site https://maurodatamapper.github.io/
* Change the "Wiki" footer link to not point to the wiki, instead it should point to the MDM documentation site
* Remove/change any further references to the obsolete wiki
