### ISSUE TITLE
Add link to documentation to home page for MDM 

### ISSUE THREAD

**Issue by theresanoble** [MauroDataMapper/mdm-ui#134]
https://maurodatamapper.github.io

Add link above to home page for all instances, in BIG BOLD Letters.. possibly flashing with a giphy so you don't miss it.

**Comment by pjmonks** [comment]
PR #127 has actually updated the footer in MDM to replace the "wiki" link with a "documentation" link - this navigates to https://maurodatamapper.github.io now since the original wiki is no longer running. Also, help icons dotted around the UI will jump to the relevant documentation page now so the content is up to date 

![image](https://user-images.githubusercontent.com/3219480/118946378-3acc7e80-b94e-11eb-8be6-dea39bbbb1c9.png)

Seeing as these changes are just waiting for release now, is there anything else to this issue that could be added, or is the above sufficient?

**Comment by pjmonks** [comment]
Moving a comment that @theresanoble made in the finished PR to here to continue the conversation:

> having a link on the home page before you log in would be very very helpful for new users. I wasn't aware there was new documentation until Ollie sent me the link this morning and I've been using MDM actively for weeks now.... Just something a bit bolder so that as a user you see it I think would be helpful for those are aren't completely comfortable in the metadata world. (if that makes sense)

In that case, how about if a new button was added to the home page content next to the "Log in" (or "Browse our models") button called "Read our docs" (or similar)? Clicking this would navigate to the new documentation site in a new browser tab, same as the footer link. Having this extra button should make it clear and looks consistent with other landing pages I've seen in other sites. See the screenshot below:

![image](https://user-images.githubusercontent.com/3219480/118956176-483a3680-b957-11eb-8d77-2465478b52d4.png)

Do you think that would work @theresanoble?

**Comment by theresanoble** [comment]
Yes!! thats perfect!

**Comment by pjmonks** [comment]
Great! I'll say this is ready to work on then.

**Comment by pjmonks** [comment]
![image](https://user-images.githubusercontent.com/3219480/119146529-a0019c00-ba42-11eb-987e-8364afb4fdeb.png)

This is what the new button looks like on the home page, appearing if logged in or not. Clicking "Learn more" goes to the documentation site (in a new browser tab).
