### ISSUE TITLE
Remove redundant code from Detailed views

### ISSUE THREAD

**Issue by gammonpeter** [MauroDataMapper/mdm-ui#139]
There is a lot of redundant code within the detailed views of most catalogue items, to improve code readable this should be reviewed and refactored to make the code more clean

**Comment by pjmonks** [comment]
Some examples I've found whilst working on adding views for Versioned Folders (looking at Data Model views as a basis):

1. Duplicate properties e.g. one called `isEditable`, another called `showEdit` - both seem to serve the same purpose despite different names
2. Code no longer in use, probably due to the latest UI layout changes by moving details into the Description tab
3. Editable forms can be easily consolidated rather than copy-pasting similar code to match models.
4. Some tabs are quite common between all views, is there a way to have a base template act for each model type?
