### ISSUE TITLE
Version graph arrow direction incompatible with label

### ISSUE THREAD

**Issue by oughnic** [MauroDataMapper/mdm-ui#239]
**Describe the bug**
label "New Model Version Of" is not compatible with the arrow direction when looking at a versioning graph using the Show Merge Graph option.

**Expected behavior**
Either reverse the arrow head or (preferred) change label to "has new version"

**Screenshots**
![image](https://user-images.githubusercontent.com/27196895/125782839-c73f6bd4-1659-468c-a7a4-be206339255f.png)

**Comment by olliefreeman** [comment]
so the label is taken from the VersionLinkType which exists, so the JSON from the API cant change the label so a label change would have to be coded into the UI which is probably to be considered as messy,
therefore the option really is to chnage the direction of the arrow. 

I suspect the JSON being supplied by the API is the cause of this issue rather than the UI, but if someone in UI can check then we may want to move this to mdm-core.

**Comment by jamesrwelch** [comment]
@olliefreeman There's a side issue which may also just be a presentation thing, or may be a bug in the database importers - the orange branch has Version 1.0.0 on it, but is coming off finalised model 1.1.0.
