### ISSUE TITLE
Allow public users to view superseded models

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#279]
The 'show superseded models' is currently in the user preferences.  It would be nice if there was also the same option on the tree view - in particular when a user is not logged in, so that public users can view superseded models.

**Comment by olliefreeman** [comment]
There are actually 2 options for superseded, the ui removed 1 a while back cos is wasn’t working.

the profile option is supposed to be “superseded document models” which makes sense as there’s little reason anyone would want to actually see these

the tree option should be “model superseded models” which should be added back in so that ppl can see the older model versions
