### ISSUE TITLE
Odd rendering/colouring in the top bar

### ISSUE THREAD

**Issue by olliefreeman** [MauroDataMapper/mdm-ui#312]
**Describe the bug**
See the screenshot, this was using firefox so it may be to do with the way browsers render colours. Or its a glitch across all browsers

You can see the words "User profile" under the name

![Screenshot 2021-09-01 at 16 49 25](https://user-images.githubusercontent.com/2587424/131703171-b728c39b-906a-414c-b37b-2ae8b5120f7c.png)

**Comment by pjmonks** [comment]
This happens in all browsers if the image for the user profile cannot be loaded. The image comes from `/api/catalogueUsers/{id}`, so if that returns a 404 then the text you are seeing is the "Alt" label all `<img>` tags should have.

This is not necessarily a bug with the UI, this is standard browser behaviour. It just looks unusual due to the colour scheme used.
