### ISSUE TITLE
Default value not able to be populated from enumerated list (of one) when adding a new profile to a data asset

### ISSUE THREAD

**Issue by PaulChapmanPM** [MauroDataMapper/mdm-ui#403]
When adding a profile to a data asset, where the profile has a default value in an enumerated field (of 1), it will not allow default choice to be completed and therefore will not allow addition of the profile to be saved. Screen shots in the attached. 
[Default value issue.docx](https://github.com/MauroDataMapper/mdm-ui/files/7661833/Default.value.issue.docx)

**Comment by jamesrwelch** [comment]
@gammonpeter are you able to take a quick look at this one this week?

**Comment by gammonpeter** [comment]
@PaulChapmanPM  if you click the validate button does the error on the enum go?

**Comment by PaulChapmanPM** [comment]
Hi Peter.  We are getting a different error before we get there now. On selecting the profile, we get:
![image](https://user-images.githubusercontent.com/89066945/146034026-80ca7bae-8dc3-4a8a-96d8-543cad86333f.png)

**Comment by PaulChapmanPM** [comment]
Hi @jamesrwelch - do you have any indication when this may drop back into someone's workstack please?

**Comment by pjmonks** [comment]
@PaulChapmanPM I'm having some trouble replicating this. Would you be able to export your profile "DD4C v0.3.01" to JSON please? I will then import it and have the correct enumerations/state as you see it, hopefully I'll then be able to see where the issue lies.

**Comment by pjmonks** [comment]
I've imported a copy of the profile used in the original issue and tried to replicate. However, I do not see the original issue happening where the default value of an enumeration profile field cannot be selected. This is the view I see when editing a profile on a new data model:

![image](https://user-images.githubusercontent.com/3219480/151541601-2e9e83ad-ca85-4a53-a2a2-b6b03d2ed5b6.png)

By setting the default value for this field, it has correctly populated it with the (one and only) enumeration value. Any other validation errors on the profile are correct, since they are required fields which need a value. When I enter values into those required fields and re-validate, the issue count decreases.

Given that this issue already seems to be fixed I will now close it.

**Comment by PaulChapmanPM** [comment]
Thanks Peter.  We had a couple of other bugs that were causing us problems, at least one of which seems to have been explained, so we'll replicate this ourselves too to make sure we're getting the same results as you and not just making mistakes in the way we are doing it.  Thanks again.
