### ISSUE TITLE
User access assignment - irrelevant access roles show up in UI

### ISSUE THREAD

**Issue by jelenadreskai** [MauroDataMapper/mdm-ui#409]
**Describe the bug**
User access assignment - irrelevant access roles show up in UI.

**To Reproduce**
1. Login as administrator, and select a folder
2. Click on User Group Access 
3. Dialog shows up assigning user groups specific access rights (Editor, Reader, Reviewer, Author, Container Administrator, Container Group Administrator

**Expected behavior**
According to the discussion in Zulip Chat, Group Content Administrator should not be listed on the folder/classification access permissions.
https://maurodatamapper.zulipchat.com/#narrow/stream/286976-users/topic/User.20Permissions/near/265664267

**Screenshots**
![image](https://user-images.githubusercontent.com/81437684/147160858-243d2202-9882-433f-ad35-8b392cd03a47.png)

**Additional context**
MDM 6.6.0/4.10.0

**Comment by pjmonks** [comment]
I cannot seem to replicate this bug. Tested on the branch I created for #755 due to a bug in the UI, this is the full list of access roles I see for a folder:

![image](https://user-images.githubusercontent.com/3219480/218982907-1fbb5e23-0726-49e0-9f2e-d8f751da9920.png)

The list of group roles is returned by the Mauro backend and it not manipulated further by the UI, so if this were a bug then it would have been caused in the backend. However, seeing as I don't see this issue anymore I will assume that it was fixed in `mdm-core`.

Closing this issue due to this no longer being an issue.
