### ISSUE TITLE
README does not explain how to get end-to-end Mauro system working

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#452]
# Description

The `mdm-ui` repo README explains how to start a developer instance of the UI, but does not actually cover how to get an equivalent `mdm-core` instance running to utilize the backend APIs. This makes it harder for new developers to get started with the project.

# Additional context

UI developers should be directed to setup [mdm-application-build](https://github.com/MauroDataMapper/mdm-application-build), which may include installing all `mdm-core` dependencies too if necessary, such as Postgres, Grails, etc

**Comment by olliefreeman** [comment]
@pjmonks actually can you write this up Into the online docs so that we can point all repos to the same page in their readme. I’d like to limit the readme to as little info as possible to make them easier to maintain and less documentation being duplicated. 

There’s a developer folder in the docs repo, I think the whole “how to setup mdm-ui, how to setup Mab, how to setup mdm-core” can all go in there. (I’ll do mdm-core bit)

**Comment by pjmonks** [comment]
@olliefreeman That would make more sense, key point being that we don't have anything written up so far to explain how to setup the whole environment. A single resource in the `docs` folder would be a good option - though is that "developer" folder public yet in the docs navigation?

**Comment by oughnic** [comment]
+1 to @olliefreeman comments.

**Comment by pjmonks** [comment]
I've created a new issue in the `docs` repo - MauroDataMapper/docs#56 - which takes @olliefreeman suggestion of writing this up in that single place rather than multiple READMEs. Therefore I'll close this issue as obsolete now.
