### ISSUE TITLE
Remove the additional call during the login process to allow the login window to disappear

### ISSUE THREAD

**Issue by olliefreeman** [MauroDataMapper/mdm-ui#484]
Currently when logging in the UI makes an additional call to `api/session/isApplicationAdministration` as soon as it receives confirmation from the API that the user is logged in. It will not close the login popup window until the response from this call is received.

The issue is that an improvement to the API to speed up the log in process itself is now returning the first call but leaving the API in a "locked" state for the user's security policy. Any subsequent calls to the API will stall until the lock has been removed via the async operation building the security policy.

This means the call to this additional endpoint is stalling for the time the policy is locked, thereby not progressing the user any further into the application.

If the UI did not make this call immediately, but rather closed the popup window and then progressed and made the call while it loaded the tree then it could allow users to possibly perform other actions.

No additional actions or endpoints are required to handle the "lock" its a built in feature to the API to just hold any calls while a policy is being updated.

**Comment by pjmonks** [comment]
I've been doing some investigation to the feasibility of this change and found that this should be doable. This was tested on branch `feature/mc-9803` from MauroDataMapper/mdm-core.

# Sign in dialog

When I've removed the `api/session/isApplicationAdministration` call temporarily from the login operation, the sign-in dialog closes pretty much immediately. This definitely gives the UX appearance of working faster.

# Dependencies on `isAdmin` flag

The call was included as part of the login operation because checking the admin state is required in numerous components. However, for the most part I've found that there are simple workarounds:

1. Remove flag check completely - code wasn't even using it
2. Code could just call `api/session/isApplicationAdministration` when required, there is usually no need to depend on this at the start of your session.
3. Or depend more on the `availableActions` list for catalogue items - sometimes the checks are to determine if you have permissions to soft/permanent delete items

There are two small cases though which could require discussion:

## Navigation Menu

The `isAdmin` flag is used on navigation menu to decide which links to display:

![image](https://user-images.githubusercontent.com/3219480/156763395-67955fdb-f451-43d8-8afe-e21aa6d875d1.png)

Because this is a key part of the layout, knowing the state of the user is pretty key and needed right at the start of the session.

My suggestion is to actually reduce this menu down. I don't believe we need every account setting section listed, instead just replace with a link to "My account settings" page (where the admin check could happen), and a "Log out" button. This could be considered a UX change as well - trying to reduce the complexity of the menu - but would need approval from @jamesrwelch before this change happened.

## Allow permissions to change on catalogue items

A catalogue item with a `availableActions` array may include the `update` action, meaning the user can (among other things) view the user/group permissions of that item.

Question for @olliefreeman - if you are an admin, would this action always be returned by the backend? If so, the `isAdmin` flag check can be safely removed.

**Comment by olliefreeman** [comment]
so yes that isApplicationAdministrator has to wait for the policy, i did try to pre-load it, but there are 2 issues with preloading

1. it may not be right due to container admins
2. that call has to be made on an unlocked policy, however the policy remains locked until the remaing parts of the policy are built, this was what i couldnt get around. If we unlock the policy nothing works, if we leave it locked theres no point prebuilding the application access as we still have to wait for the lock to remove

wrt `update` this actually relates to the ability to use the `PUT` call to update the object, `isApplicationAdministrator` is actually relevant to the "application" NOT the resource, so its presence shouldnt actually denote the ability to do actions on a resource.
There are 2 types of "admin" user who would not be able to affect a resource, which i'm not sure we're using yet.

1. User admin
2. UserGroup admin

These 2 roles allow users to add/remove users and groups, so they would need access to the admin pages.

Having said all that the `isApplicationAdministrator` endpoint is specifically to denote that the user has the role application_admin or site_admin in which case...yes they will have full access to ALL resources.

There is probably a piece of work to check who can access what wrt application roles, whcih could be done as part of the aforementioned "refactor of admin menu"

**Comment by pjmonks** [comment]
@jamesrwelch - After doing my refactoring I've found that the navigation menu isn't really an issue actually. What will happen now is:

1. Login endpoint returns with success
2. Login dialog is then closed
3. A notification is broadcast to other listening components that the login was successful
4. The header component picks this up and then call `isApplicationAdministrator`

The worst that will happen is that the user profile will appear in the header, then shortly update again after to show any admin related changes (display role, expand menu with more options etc). We've still maintained the speed update though.
