### ISSUE TITLE
Spurious profiles appearing in profile dropdown when a profile is added to a catalogue item

### ISSUE THREAD

**Issue by THeneghan** [MauroDataMapper/mdm-ui#565]
# Description
Applies to version MDM7.1

When adding a finalised profile stored in one folder (catalogue item independent) to a catalogue item (applies to all catalogue item types) in another folder, all of the finalised profiles from the profile folder appear in the drop down

# Steps to reproduce
Create two distinct folders. 
Populate one folder with finalised profiles (PSP 5.1 added to data model and all data element)
Create a folder/data model/data class/data element in the other folder.
Add one of the data profiles to any of the catalogue items.
Witness all finalised profiles appearing in profile drop down menu.

# Expected behavior

Expect to see only the profile that has been added to appear in the drop down menu.

# Screenshots
![Screenshot 2022-06-17 at 16-53-31 Data Element - yu](https://user-images.githubusercontent.com/76405616/174334601-85e045a1-56eb-43e5-b5d4-70bc360df3a3.png)

# Environment

## Desktop 

Please complete the following information:
- OS: Ubuntu 22.04 (64-bit)
- Firefox
- Version 101.0

**Comment by joe-crawford** [comment]
Hi Tom,

Do the profiles possibly have the same metadata namespace? Only the metadata namespace is checked to find whether a profile in use (partly because in theory different versions of the profile could have different sets of fields).

In your example the namespaces could be values such as `uk.gov.ons.department.attributes`, `uk.gov.ons.department.database`, etc.

**Comment by THeneghan** [comment]
Hi Joe, 

Thanks for the speedy reply. Will try and investigate today and get back to you (**I think they do share the same namespace**). I was getting a similar issue with later finalised versions of profiles e.g. I would have profiles Tables 0.0.1, Tables 0.0.2, Tables 0.0.3; I'd add Tables 0.0.3 and the other two profiles would also appear. It sounds like this is a similar issue with shared namespaces.

**Comment by joe-crawford** [comment]
Yes, multiple versions of the same profile appearing when one is applied is currently expected when they have a shared metadata namespace. I agree it isn't quite ideal in the UI however the reason is also because the different versions of a profile could have different sets of fields, but also the version of the profile that was actually entered by the user is not saved on the backend. So the older versions are shown in case there is a profile field in them that has been removed from the latest profile version.

You could try adding a version suffix to the metadata namespace to hide the older versions, e.g. `[...].attributes.v1`, `[...].attributes.v2`, etc.

**Comment by THeneghan** [comment]
Thanks Joe.
I had been sharing a namespace - now given each profile its own unique namespace and the problem's been resolved. Thanks for the feedback regarding duplicate profiles.
Will close the thread.
