### ISSUE TITLE
Improve the element selection drop-down

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#577]
# Overview

The current element section drop-down Is quite basic and hard to use on larger models.

<img width="1195" alt="Screenshot 2022-06-30 at 14 37 05" src="https://user-images.githubusercontent.com/1869668/176691291-f82a80a1-658a-471e-8d99-6b6cbf3af731.png">

Some suggestions, which need prioritising for ease of implementation: 
- Show the elements as part of a tree view, so you can see where each element is in the tree
- (or, perhaps as a temporary measure, showing the breadcrumbs for each element)
- Allow users to select all elements from a particular data class
- Filtering by name

# Tasks

- [x] #594
- [x] #595

**Comment by pjmonks** [comment]
Possible ideas we could update the UI to support not just Data Elements but any type (particularly when it comes to issues #582, #583 and #584):

![ProposedItemSelectionUI](https://user-images.githubusercontent.com/3219480/177181861-0ea0e48a-bc02-4eeb-bca1-bec69fe26e21.png)

For manual selection of items:

1. Display a tree view listing all child elements under a model - Data Classes and Terms.
2. Display a list view for displaying other kinds of elements - Data Types, Data Elements etc
3. If the user clicks on an item in the tree view, they will be able to add the Data Class/Term to the selected items list
4. Clicking on a tree view item will also potentially update the list view to show items under that DC/Term e.g. what Data Elements are available
5. If the user clicks on a list view item, then those too can be added to the selected item list.
6. The selected item list then becomes the full set of catalogue items to bulk edit in the spreadsheet view.

Some actions could also be automated to make it more efficient, e.g.

1. Select all Data Classes
2. Select all Data Elements
3. etc

To progress further with this issues, we would need either further suggestions or approval from @jamesrwelch if this is a suitable way forward.

**Comment by pjmonks** [comment]
I've researched how the current bulk editor works at the moment, and have come to the realisation that there are two key constraints we should follow when selecting catalogue items and profiles:

1. All items selected _must_ be of the same domain type i.e. all Data Elements, all Data Types, etc but never a mixture of multiple domains.
2. All profiles used _must_ be able to be applied to the domain type chosen above.

The reason for the single domain type restrictions is to do with the Mauro profile endpoints being tied to particular domains e.g. `/api/{domainType}/{id}/profiles/getMany`. While it may be possible to actually support multiple domain types in the editor and reference multiple profile endpoints in the same operation, this will greatly increase the complexity both for the user and the codebase. The advantages of focusing on one domain at a time are:

1. It will be easier for the user to select catalogue items, only focusing on what is required.
2. Complex determinations of which profiles are allowed on which items can be sidestepped for now - because we would know that all selected profiles are supported.

Based on these restrictions, I am proposing the following UI changes to support this issue:

# Item selection

![Bulk edit UI ideas-Item Selection drawio](https://user-images.githubusercontent.com/3219480/177353795-422f76c6-f03d-4a48-85f0-9b292a6bb90a.png)

The above mockup highlights the following:

1. First, a user must select which domain type to use for item selection. This would depend on the root item the bulk editor started with - a Data Model would allow Data Classes/Types/Elements for instance.
2. Once a domain has been chosen, the item selection list would be populated with all possible items under the root item matching that domain type e.g. all Data Elements. Paths would be displayed next to each list item to show hierarchy.

A list view will be used instead of a more complex tree view to try and simplify the UI. The list view will need to support multiple methods of item selection, such as:

1. Single selection per item
2. Manual multi-selection
3. Select all

And to aid the selection process, the list will probably need filtering and sorting options as well.

# Profile selection

![Bulk edit UI ideas-Profile selection drawio](https://user-images.githubusercontent.com/3219480/177355218-ea706943-901c-412f-92bd-b28b3829b9b2.png)

The current bulk editor UI makes the user select the profiles upfront before editing them. This mockup shows an alternative where profile tabs can be added/removed when the user chooses. A "Default" profile tab (see #578) could always be visible, yet other profiles could be added at will.

# Next steps

1. Confirm with @jamesrwelch whether this proposal is acceptable. Particular the constraints on only allowing one domain to be edited at a time.
2. Define further sub-tasks to break up this work.
